let current_version = 0.3;
let languageTranslation = {
  en: {
    start_project_btn: "Start Project",
    artistText: "Artist",
    songText: "Song's name",
    welcomeText:
      "Welcome to mytranshelper, please login first and then click the start project button so that you can start your lyrics translation project.",
    welcomeTextHeader: "Getting Started",
    welcomeTextDrawer: "Welcome",
    welcomeTextDrawerLogin: "Welcome back,",
    dialogTitleText: "Please enter your project info",
    uploadBtn: "Upload lyrics",
    title: "Home page",
    logpage: "Update logs",
    logout_btn: "Log out",
    login_btn: "Log in",
    loadProjectText: "加载项目",
    projectTag: "Projects",
    loadProject: "Load Project",
    editing_page_title: "Lyrics Translation",
    translationProject: "Translation Project",
    original_text: "Original",
    translation_text: "Translation",
    saving_status: "Saved",
    words: "Editing in words",
    sentences: "Editing in sentences",
    type_selector: "Choose the way to display the text",
    doc_header: "Read the docs",
    doc_text: "Read some story about developing(Chinese only)",
    version: `Current version ${current_version}`,
    "header_0.05": "Version0.05",
    "time_0.05": "2018/8/05",
    "content_0.05":
      "Set up the basic UI looking and added the lyrics editing function",
    "header_0.1": "Version0.1",
    "time_0.1": "2018/8/09",
    "content_0.1": "Added the list of the songs which user uploaded",
    "header_0.2": "Version0.2",
    "time_0.2": "2018/8/11",
    "content_0.2":
      "Improved the way to display the lyrics. Redesign the mobile version and added the docs",
    home: "Home",
    logs: "Develop logs",
    createTimedLyrics: "Create timed lyrics",
    usingApplemusic: "Play music from Apple Music",
    uploadthetimedlyrics: "Timed lyrics data has been uploaded",
    currentInfo:
      "Problem: Won't be able to highlight the word which has short period.",
    not_login: "Not login"
  },

  zh: {
    start_project_btn: "开始项目",
    artistText: "歌手",
    songText: "歌名",
    lyricsText: "歌词",
    welcomeText:
      "欢迎来到歌词翻译网站，请先登录，之后轻点下方的开始项目按钮，便可以轻松创建属于你的歌词翻译项目。",
    welcomeTextHeader: "开始使用",
    welcomeTextDrawer: "欢迎",
    welcomeTextDrawerLogin: "欢迎回来,",
    dialogTitleText: "请输入你的项目信息",
    uploadBtn: "上传歌词",
    title: "主页面",
    logpage: "更新记录",
    logout_btn: "登出",
    login_btn: "登入",
    signUp_btn: "注册",
    loadProjectText: "加载项目",
    projectTag: "全部项目",
    loadProject: "读取项目",
    translationProject: "翻译工程",
    editing_page_title: "歌词翻译",
    original_text: "原文",
    translation_text: "译文",
    saving_status: "已保存",
    words: "按照单词方式编辑",
    sentences: "按照句子方式编辑",
    type_selector: "选择文本显示方式",
    doc_header: "阅读文档",
    doc_text: "阅读有关开发的一些故事",
    version: `当前版本 v${current_version}`,
    "header_0.05": "版本0.05",
    "time_0.05": "2018/8/05",
    "content_0.05":
      "初步设计了整体UI以及加入了歌词翻译功能，增加了歌曲编辑功能",
    "header_0.1": "版本0.1",
    "time_0.1": "2018/8/09",
    "content_0.1": "增加了歌曲列表，增加了多语种翻译",
    "header_0.2": "版本0.2",
    "time_0.2": "2018/8/11",
    "content_0.2":
      "增加了改进了用户编排歌词的方式，专门对手机版本进行了优化，改进了UI设计并且增加了文档",
    home: "主界面",
    logs: "开发日志",
    createTimedLyrics: "创建同步歌词",
    usingApplemusic: "播放苹果音乐歌曲",
    uploadthetimedlyrics: "同步歌词数据已经上传，请刷新页面",
    currentInfo: "问题：在歌词显示的时候会出现间隔过短导致无法高亮单词的问题。",
    sentencesmobile: "以手机样式编辑",
    not_login: "尚未登陆"
  }
};
export default languageTranslation;
